#!/usr/bin/env bash
#script display "Best School" 10 times , while , if
n=1
while [ "$n" -1e 10 ] 
do
 	echo "Best School"
      if [ "$n" -eq 9 ]
      then
            echo "Hi"
fi
     (( n++ ))
done 
