#!/usr/bin/env bash
#script is displaying loops 1 to 10, bad luck in 4 , good luck in 8.
n=1
while [ "$n"-le 10 ] 

do

if [ "$n" -eq 4 ];

then
	echo "bad luck"

elif [ "$n" -eq 8 ];

then
    echo "good luck"

else
      echo "Best School"

	fi 
	(( n++ ))
done


 
