#!/usr/bin/env bash
#script displays numbers from 1 to 20
# 4 , bad luck from china, 9 japan , 17 italy
n=1
while [ "$n" -le 20 ] 
do 
	echo "$n"
 case $n in 

  4) echo "bad luck from China";;
  9) echo "bad luck from Japan";;
  17) echo "bad luck from Italy";;
 esac 
     (( n++ ))
done
