#!/usr/bin/env bash
#script that displays To inf and beyond indefinitely 
#sleep 2 in between each iteration

while TRUE
do 
    echo "To infinity and beyond"
  
    sleep 2 

trap 'echo "I am invincible!!!"' SIGTERM

done 
